Remove deprecated -teal image references
rancher/elemental-docs pull request #327
Opened 2024-04-24 10:51 UTC by anmazzotti

Closes #326

2024-04-24 10:55 UTC, kkaempf requested changes

2024-04-24 10:55 UTC, kkaempf commented on versioned_docs/version-1.4/architecture.md
> +Elemental OS is built on top of SUSE Linux Enterprise (SLE) Micro for Rancher using the Elemental stack.
There's no "Elemental OS" - there's only SL(E) Micro as an OS.

2024-04-24 10:55 UTC, kkaempf commented on versioned_docs/version-1.4/customizing.md
> +FROM registry.suse.com/suse/sle-micro/5.5:2.0.2
why not `5.5:latest` ?

2024-04-24 10:55 UTC, kkaempf commented on versioned_docs/version-1.4/partials/_quickstart-prereqs.md
> +  * Hint 4: A minimum volume size of 25 GB is recommended. See the [Elemental Teal partition table](installation#deployed-elemental-partition-table) for more details
There's still "Elemental Teal" here 😉

2024-04-24 10:55 UTC, kkaempf commented on versioned_docs/version-1.4/rancher-vmware.md
> +./elemental-iso-add-registration initial-registration.yaml /home/elemental-iso/sl-micro-6.0-baremetal.x86_64.iso
No, please no mentioning of micro 6.0 before its release

2024-04-24 11:01 UTC, anmazzotti commented on versioned_docs/version-1.4/customizing.md
> +FROM registry.suse.com/suse/sle-micro/5.5:2.0.2
Too much copy paste, thank you.

2024-04-30 10:15 UTC, fgiudici approved these changes
looks good here!

2024-04-30 10:15 UTC, fgiudici commented on versioned_docs/version-1.4/installation.md
> +ne of the characteristics of Elemental OSes is the setup of an immutable root
typo
```suggestion
One of the characteristics of Elemental OSes is the setup of an immutable root
```

2024-05-01 08:21 UTC, merged