Architecure section rework
rancher/elemental-docs pull request #336
Opened 2024-05-15 07:28 UTC by fgiudici

fixes #334

2024-05-15 17:42 UTC, fgiudici commented
While the architecture section is still way incomplete, seems to me this is an improvement to what we have right now.
Opening to reviews, I would focus on fixing what is dealt here, leaving missing pieces to forthcoming PRs.

2024-05-16 08:44 UTC, anmazzotti requested changes
I would reconsider the creation of additional CRDs documents, and extend the existing reference ones instead, for example simply adding the new documentation you wrote at the top, as a generic introduction.

A part from that, all looks very good! Nice improvements!

2024-05-16 08:44 UTC, anmazzotti commented on docs/architecture-components.md
> +* the [``elemental``](#elemental) command line tool
These anchors are not correct I think.

2024-05-16 08:44 UTC, anmazzotti commented on docs/architecture-components.md
> +The ``elemental`` tool is part of the Elemental Toolkit project.
```suggestion
The ``elemental`` tool is part of the <Vars name="elemental_toolkit_name" link="elemental_toolkit_url" /> project.
```

2024-05-16 08:44 UTC, anmazzotti commented on docs/custom-resources.md
I do feel like instead of having new documents here, we could just improve the existing reference documents for each resource.

2024-05-16 14:42 UTC, fgiudici commented on docs/architecture-components.md
> +* the [``elemental``](#elemental) command line tool
good catch!

2024-05-16 15:48 UTC, fgiudici commented on docs/custom-resources.md
yeah, much better

2024-05-16 17:10 UTC, fgiudici commented
Last little change on top: minor changes to the architecture image.

2024-05-17 10:57 UTC, davidcassany approved these changes
Looks good! Thanks for reworking this part. I like it, short and properly divided :+1:

2024-05-17 13:17 UTC, merged