Add creation of custom bootable install media
rancher/elemental-docs pull request #46
Opened 2023-01-31 12:44 UTC by dgiebert

2023-01-31 12:56 UTC, kkaempf requested changes
Use images from `stable` only

2023-01-31 12:56 UTC, kkaempf commented on docs/customizing.md
> +FROM registry.opensuse.org/isv/rancher/elemental/teal53/15.4/rancher/elemental-node-image/5.3:VERSION
```suggestion
FROM registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-node-image/5.3:VERSION
```

2023-01-31 12:56 UTC, kkaempf commented on docs/customizing.md
> +FROM registry.opensuse.org/isv/rancher/elemental/teal53/15.4/rancher/elemental-node-image/5.3:latest as os
```suggestion
FROM registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-node-image/5.3:latest as os
```

2023-02-01 08:58 UTC, kkaempf commented
It's not immediately clear to me what this PR accomplishes.

Can you please elaborate more on the motivation and the problem you're solving here ?

2023-02-08 09:51 UTC, kkaempf commented
Ping @dgiebert 😉

2023-02-08 10:07 UTC, dgiebert commented
Users will be able to create custom images to customize the boot process; this includes:
- Custom or extra modules that are needed during boot.
- Embed custom configuration 
- Any other patching of the initially booted operating system 

This will also make it easier to roll out custom builds in air-gapped scenarios.

2023-02-08 12:27 UTC, kkaempf approved these changes

2023-02-08 12:28 UTC, merged